git clone https://github.com/cinquemb/WifiBruteCrack.git
git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git
git clone https://github.com/awkman/pywifi.git
git clone https://github.com/53k41iga/wpa2-psk-brute-force.git
git clone https://github.com/madeindjs/Wifi_BruteForce.git
git clone https://github.com/derv82/wifite2
git clone https://github.com/aircrack-ng/aircrack-ng
git clone https://github.com/threat9/routersploit
git clone https://github.com/wifiphisher/wifiphisher
git clone https://github.com/WiPi-Hunter/PiDense
git clone https://github.com/aress31/wirespy
git clone https://github.com/3xploitGuy/lazyaircrack
git clone https://github.com/MS-WEB-BN/h4rpy
